[build]
command = "pnpm build"
publish = ".output/public"

[build.environment]
NODE_VERSION = "22"
REPOSITORY_TYPE = "seed"

[context.deploy-preview]
command = "pnpm build"

[context.deploy-preview.environment]
REPOSITORY_TYPE = "seed"
